Chill\ReportBundle\Entity\Report:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        date:
            type: datetime
        scope:
            type: string
            length: 255
            nullable: true # TO REMOVE IF SCOPE IS USED
        cFData:
            type: json_array
    manyToOne:
        user:
            targetEntity: Chill\MainBundle\Entity\User
        person:
            targetEntity: Chill\PersonBundle\Entity\Person
        cFGroup:
            targetEntity: Chill\CustomFieldsBundle\Entity\CustomFieldsGroup
    lifecycleCallbacks: {  }