Chill\ReportBundle\Entity\Report:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        date:
            type: datetime
        cFData:
            type: json_array
    manyToOne:
        user:
            targetEntity: Chill\MainBundle\Entity\User
        person:
            targetEntity: Chill\PersonBundle\Entity\Person
        scope:
            targetEntity: Chill\MainBundle\Entity\Scope
        cFGroup:
            targetEntity: Chill\CustomFieldsBundle\Entity\CustomFieldsGroup
    lifecycleCallbacks: {  }