report_select_type:
    pattern:  /person/{person_id}/report/select/type/for/creation
    defaults: { _controller: "ChillReportBundle:Report:selectReportType" }
    options:
        menus:
            person:
                order: 100
                label: Add a report
report_new:
    path:     /person/{person_id}/report/cfgroup/{cf_group_id}/new
    defaults: { _controller: "ChillReportBundle:Report:new" }

report_create: 
    path:     /person/{person_id}/report/cfgroup/{cf_group_id}/create
    defaults: { _controller: "ChillReportBundle:Report:create" }
    requirements: { _method: post }

report_list: 
    path:     /person/{person_id}/report/list
    defaults: { _controller: "ChillReportBundle:Report:list" }
    options:
        menus:
            person:
                order: 101
                label: Report list
report_show:
    path:     /person/{person_id}/report/{report_id}/show
    defaults: { _controller: "ChillReportBundle:Report:show" }

report_edit:
    path:     /person/{person_id}/report/{report_id}/edit
    defaults: { _controller: "ChillReportBundle:Report:edit" }

report_update:
    path:     /person/{person_id}/report/{report_id}/update
    defaults: { _controller: "ChillReportBundle:Report:update" }
    requirements: { _method: post|put }