report_select_type:
    pattern:  /person/{person_id}/report/select/type/for/creation
    defaults: { _controller: "ChillReportBundle:Report:selectReportType" }
    options:
        menus:
            person:
                order: 100
                label: Add a report
report_new:
    path:     /person/{person_id}/report/cfgroup/{cf_group_id}/new
    defaults: { _controller: "ChillReportBundle:Report:new" }

report_create: 
    path:     /person/{person_id}/report/cfgroup/{cf_group_id}/create
    defaults: { _controller: "ChillReportBundle:Report:create" }
    requirements: { _method: post }

report_list: 
    path:     /person/{person_id}/report/list
    defaults: { _controller: "ChillReportBundle:Report:list" }
    options:
        menus:
            person:
                order: 101
                label: Report list

report_show:
    path:     /person/{person_id}/report/{id}/show
    defaults: { _controller: "ChillReportBundle:Report:show" }

cl_custom_fields_report:
    resource: "@ChillReportBundle/Resources/config/routing/report.yml"
    prefix:   /report