report_select_type:
    pattern:  /person/{person_id}/report/create
    defaults: { _controller: "ChillReportBundle:Report:selectReportType" }
    options:
        menus:
            person:
                order: 100
                label: Add a report

cl_custom_fields_report:
    resource: "@ChillReportBundle/Resources/config/routing/report.yml"
    prefix:   /report