services:
#    chill_report.example:
#        class: Chill\ReportBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
services:
            
    chill.report.search:
        class: Chill\ReportBundle\Search\ReportSearch
        arguments:
            - '@doctrine.orm.entity_manager'
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: chill.search, alias: 'report' }
            
    chill.report.timeline:
        class: Chill\ReportBundle\Timeline\TimelineReportProvider
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: chill.timeline, context: 'person' }