services:
#    chill_report.example:
#        class: Chill\ReportBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
services:
    chill.report.routing_loader:
        class: Chill\ReportBundle\Routing\RoutesLoader
        tags:
            - { name: routing.loader }
            
    chill.report.search:
        class: Chill\ReportBundle\Search\ReportSearch
        arguments:
            - '@doctrine.orm.entity_manager'
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: chill.search, alias: 'report' }