services:
#    chill_report.example:
#        class: Chill\ReportBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
services:
    chill.report.routing_loader:
        class: Chill\ReportBundle\Routing\RoutesLoader
        tags:
            - { name: routing.loader }