language: php
php:
- 5.5
- 5.6
- hhvm-nightly
matrix:
  allow_failures:
  - php: hhvm-nightly
addons:
  postgresql: '9.3'
sudo: false
install:
- composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH
- composer install --dev --no-interaction
- cp Tests/Fixtures/App/app/config/parameters.travis.yml Tests/Fixtures/App/app/config/parameters.yml
before_script:
- psql -c 'create database test0;' -U postgres
- psql -d test0 -c 'CREATE EXTENSION unaccent;' -U postgres
- php Tests/Fixtures/App/app/console --env=test cache:warmup
- php Tests/Fixtures/App/console assets:install Tests/Fixtures/App/web
- php Tests/Fixtures/App/app/console doctrine:migrations:migrate --no-interaction
- php Tests/Fixtures/App/app/console doctrine:fixtures:load --env=test --no-interaction
script: phpunit --coverage-text
notifications:
  email:
  - info@champs-libres.coop
env:
  global:
    secure: WUAweJ9uyCNVQsv8OOD5jofcxSlRLHbI9HBsDDdSuPVLhCcJCLRdQ312wtn5ckfy3pe+aKaijrM/rhd0NQ6lwCkcYAXcikug9k5tf2BJ0H7AJnqe56/cQSrXvxV8n6L1S2xk4AugG/k6PngZQeca5k/34jJ9ViI06V2+r4UrL7w=
