report:
    path:     /
    defaults: { _controller: "ChillReportBundle:Report:index" }

report_edit:
    path:     /{id}/edit
    defaults: { _controller: "ChillReportBundle:Report:edit" }

report_update:
    path:     /{id}/update
    defaults: { _controller: "ChillReportBundle:Report:update" }
    requirements: { _method: post|put }

report_delete:
    path:     /{id}/delete
    defaults: { _controller: "ChillReportBundle:Report:delete" }
    requirements: { _method: post|delete }
